apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: was
  labels:
    app.kubernetes.io/name: was
    app.kubernetes.io/part-of: de-ai-12
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was

  minReplicas: 2
  maxReplicas: 4

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
