apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: de-ai-12
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
