apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: de-ai-12

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: WAS_IMAGE
  newName: 827913617635.dkr.ecr.us-east-1.amazonaws.com/de-ai-12-devops-tf-eks-auto-dev/was
  newTag: 34a69185313a
- name: WEB_IMAGE
  newName: 827913617635.dkr.ecr.us-east-1.amazonaws.com/de-ai-12-devops-tf-eks-auto-dev/web
  newTag: 34a69185313a
